### ISSUE TITLE
ログアウトボタンの作成

### ISSUE THREAD

**Issue by annin401** [challecara-wakaba/anonymous_chat#146]
サイドメニューにログアウトボタンをつける

**Comment by cobaltbluesky** [comment]
src/components/sidemenu.jsの中にlogoutボタンを配置したので~~ミヤハラ~~Cioccolato58240はCSSをつけやがれください

**Comment by Cioccolato0013** [comment]
人の学籍番号をさらさないこと
<s>s58224st@kurume.kosen-ac.jp</s>

**Comment by cobaltbluesky** [comment]
おわり
Cioccolato0013
