### ISSUE TITLE
スレッド追加フォームの作成

### ISSUE THREAD

**Issue by annin401** [challecara-wakaba/anonymous_chat#16]
### スレ立てボタンを押したら出てくるフォームを作る
- コンポーネント名はmakeThreadForm.jsで

#### 実現したい仕様
- タイトルは入力必須に
- タイトルには「(例)物理 過去問 [2]-(1)」みたいにプレースホルダーで例を表示する
- 質問内容には「(例)この問題の解き方がわかりません]みたいにプレースホルダーで例を表示する

**Comment by annin401** [comment]
よく考えたら教科ごとにチャンネル立てているはずだから，タイトルのプレースホルダーには「過去問　[2]-(1) 力のモーメント」とかの方がいいかも

**Comment by Cioccolato0013** [comment]
上の3つの使用は実装したので
次は投稿ボタンなどの配置をします

**Comment by annin401** [comment]
あとするタスク
- タグ選択画面を仕様案どうりつける
