### ISSUE TITLE
スレッド画面を作る

### ISSUE THREAD

**Issue by cobaltbluesky** [challecara-wakaba/anonymous_chat#2]
メニュー画面はまだつくらない。
仕様案をもとにReactで大体の形を作る。

**Comment by annin401** [comment]
ルーティングはせずに，npm startするとその画面が現れるようにする

**Comment by annin401** [comment]
実機（iPhone）で
- カーソルの移動をするとバグる
- 予測変換と入力欄が重なる

という問題が発生している
